export const misconceptions = [
  {
    id: 'incomplete-distribution',
    misconception: 'Incomplete Distribution',
    description: 'Forgot to distribute to all terms',
    topics: ['Expanding and factorising'],
    wrong: '(x + 2)² = x² + 4',
    steps: [
      { expression: '(x + 2)²', label: 'Start here' },
      { expression: '(x + 2)(x + 2)', label: 'Expand the square' },
      { expression: 'x·x + x·2 + 2·x + 2·2', label: 'Multiply each term (this is where the mistake happens)', highlight: true },
      { expression: 'x² + 2x + 2x + 4', label: 'Combine like terms' },
      { expression: 'x² + 4x + 4', label: 'Final answer' },
    ],
    correct: 'x² + 4x + 4',
    hint: 'When you square a binomial, do you need to multiply more than just the first and last terms?',
    explanation: 'When expanding (x + 2)², you need to use the distributive property twice. Each term in the first binomial must multiply with each term in the second. The middle terms (x·2 and 2·x) combine to give 4x, which is the part that was missing.',
  },
  {
    id: 'sqrt-distribution',
    misconception: 'Square Root Distribution',
    description: 'Can\'t distribute square root over addition',
    topics: ['Indices and surds'],
    wrong: '√(a + b) = √a + √b',
    steps: [
      { expression: '√(a + b)', label: 'Start here' },
      { expression: '√9 + √16', label: 'Let\'s test with numbers: a=9, b=16' },
      { expression: '3 + 4 = 7', label: 'Using the wrong rule gives 7' },
      { expression: '√(9 + 16) = √25', label: 'But actually, 9 + 16 = 25' },
      { expression: '√25 = 5', label: 'And √25 = 5, not 7!' },
    ],
    correct: 'Square roots do NOT distribute over addition. √(a + b) ≠ √a + √b',
    hint: 'Try substituting numbers: what is √(9 + 16)? What is √9 + √16? Are they the same?',
    explanation: 'Square roots (and most functions) do not distribute over addition. This is a fundamental difference from multiplication, where √(ab) = √a · √b does work. When you see √(a + b), you must simplify what\'s inside the square root first, then take the square root of the result.',
  },
  {
    id: 'exponent-rules',
    misconception: 'Exponent Rules Mixed Up',
    description: 'Added exponents instead of multiplying',
    topics: ['Indices and surds'],
    wrong: '(x²)³ = x²⁺³ = x⁵',
    steps: [
      { expression: '(x²)³', label: 'Start here' },
      { expression: 'x² · x² · x²', label: 'This means x² multiplied by itself 3 times' },
      { expression: 'x^(2+2+2)', label: 'When multiplying powers, add the exponents' },
      { expression: 'x^(2·3) = x⁶', label: 'Which is the same as multiplying: 2 × 3' },
    ],
    correct: 'x⁶',
    hint: 'When you multiply powers with the same base, what do you do with the exponents—add or multiply?',
    explanation: 'When you have (x²)³, you\'re multiplying x² by itself 3 times. The power rule for exponents states: (xᵐ)ⁿ = x^(m·n). So you multiply the exponents: 2 × 3 = 6, giving x⁶. Don\'t confuse this with x^(m+n), which happens when you multiply x^m · x^n (same base, different multiplications).',
  },
]
